[package]
name = "truthbound"
version = "1.0.0"
authors = []

[addresses]
truthbound_addr         = '_'
escalation_manager_addr = '_'
treasury_addr           = '_'


[dev-addresses]
truthbound_addr         = '0x111'
escalation_manager_addr = '0x222'
treasury_addr           = '0x333'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]